/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class work_android_smartbow_com_wallet_copy_LearnActivity */

#ifndef _Included_work_android_smartbow_com_wallet_copy_LearnActivity
#define _Included_work_android_smartbow_com_wallet_copy_LearnActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     work_android_smartbow_com_wallet_copy_LearnActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_work_android_smartbow_com_wallet_copy_LearnActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
