/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class work_android_smartbow_com_wallet_copy_CMakeActivity */

#ifndef _Included_work_android_smartbow_com_wallet_copy_CMakeActivity
#define _Included_work_android_smartbow_com_wallet_copy_CMakeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     work_android_smartbow_com_wallet_copy_CMakeActivity
 * Method:    maxFromJNI
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_work_android_smartbow_com_wallet_copy_CMakeActivity_maxFromJNI
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     work_android_smartbow_com_wallet_copy_CMakeActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_work_android_smartbow_com_wallet_copy_CMakeActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
